artifacts_roots: artifacts

data_ingestion_config:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/subilVJ/data_file/raw/refs/heads/main/well_data_standard.zip
  local_data_file: artifacts/data_ingestion/data_zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/well_data_standard.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/well_data_standard.csv
  train_data_path: artifacts/data_transformation/train_csv
  test_data_path : artifacts/data_transformation/test_csv
  train_model_data: artifacts/data_transformation/train_model_data_csv
  test_model_data: artifacts/data_transformation/test_model_data_csv
  preprocessor_obj_file_path: artifacts/preprocessor.pkl


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_model_data_csv
  test_data_path: artifacts/data_transformation/test_model_data_csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test_model_data_csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
