artifacts_roots: artifacts

data_ingestion_config:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/subilVJ/data_file/raw/refs/heads/main/well_data_standard.zip
  local_data_file: artifacts/data_ingestion/data_zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/well_data_standard.csv
  STATUS_FILE: artifacts/data_validation/status.txt


